openapi: 3.0.0
info:
  title: Secure ToDo API
  version: 1.0.0
  description: A simple Flask API for managing tasks

servers:
  - url: http://localhost:5000

paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: API is running

  /todos:
    get:
      summary: Get all todos
      responses:
        '200':
          description: A list of todos

  /hello/{name}:
    get:
      summary: Greet the user
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Greeting message
